### PR TITLE
Add non-equilibrium calculations option

### PR DESCRIPTION
**Pull request by suzil**
https://user-images.githubusercontent.com/13723264/104112059-b1c27e00-52af-11eb-9d1a-65dd5bc225bf.mov

Let me know if there are any UI tweaks I can do related to this, eg. whether the option should be ordered differently.

Refs: #150

### CODE REVIEW

**Comment by erwanp** [comment]
It's really great, cleans up the space!  I would have minor modifications  : 

- [ ] you click the option at the top but the new buttons appear at the bottom. I'd move the "use nonequilibrum" option just above "Simulate an experimental slit" so your eyes don't have to move too much.
- [ ] Is it possible to initialize the noneq temperatures with the value of Tgas at runtime ? (maybe complicated for nothing). 
- [ ] Order : I would do Tvib, Trot, Tgas.  @minouHub / @gugzy : future user insight : is "Tgas" clear enough that we're talking about the Translational temperature in this case ? Or should we rename / add new button with to "Ttrans"

**Comment by gugzy** [comment]
Tgas is fine, it's obvious it is the translational temperature. I will order it Tgas, Trot Tvib tho. And what do you take in that case for Tel? That should be clarified if we can't choose it.

**Comment by erwanp** [comment]
As long as we only have infrared databases the electronic temperature makes no difference, so let's not clutter the UI with this ! 
Ok for Tgas > Trot > Tvib !

**Comment by suzil** [comment]
https://user-images.githubusercontent.com/13723264/104137879-af226000-5365-11eb-88ae-f02a682f23e5.mov

> you click the option at the top but the new buttons appear at the bottom. I'd move the "use nonequilibrum" option just above "Simulate an experimental slit" so your eyes don't have to move too much.

Done.

> Is it possible to initialize the noneq temperatures with the value of Tgas at runtime ? (maybe complicated for nothing).

Done.

> Ok for Tgas > Trot > Tvib !

Done.

**Comment by minouHub** [comment]
hi,
Sorry for the delay, but can I try this online or is it just local yet? https://www.radis.app/
Minou

**Comment by erwanp** [comment]
Amazing @suzil , let's merge !

@minouHub this last change is only local for the moment. I don't know if the Heroku server updates automatically. We'll see ;)

**Review by erwanp — APPROVED** [review]

**Comment by minouHub** [comment]
Not online yet. Can't wait !!!

**Comment by suzil** [comment]
> Heroku server updates automatically

It should

**Comment by erwanp** [comment]
And it did ! https://radis.app/ 👍

**Pull request merged**
