### PR TITLE
Add support for specifying multiple molecules

### PR DESCRIPTION
**Pull request by suzil**
https://user-images.githubusercontent.com/13723264/104826991-01102d80-581f-11eb-8946-899342b972b1.mov

Feedback always appreciated 🙂  Not sure what to give the plot title also.

### CODE REVIEW

**Comment by erwanp** [comment]
The backend uses the RADIS implementation of multiple molecule through a single calc_spectrum call (https://github.com/radis/radis/pull/108), so interaction between multiple molecules are taken into account : on the physics side we're good !! 👍 

On the UX side, I don't really like the large space lost by the new "Molecule" / "Mole fraction" line, and the Table feeling because of the border around "CO" and "0.1" in the example.
- I'd try to keep the initial feeling by default, which is very clean !
- What do you think of a small "(+)"  button on the left (right?) side of the initial molecule, with a minimal design, that would be your "Add" button. 
- The new molecules would come with a minimal Delete button instead of Add, for instance a ❌.

Quick Paint example : 

image

Note that in this design, I cannot delete the 1st one as you do in your example. However, I think it's fine (there aren't so many values to re-copy if needed), and it makes the interface cleaner !

**Comment by suzil** [comment]
New iteration of the design 🙂  let me know what to change @erwanp 

https://user-images.githubusercontent.com/13723264/105260522-8bc09780-5b53-11eb-808d-7b6afd70b2ad.mov

**Comment by erwanp** [comment]
Amazing @suzil , I love the buttons : clear and clean !!

Is it possible to automatically focus/select the new molecule selector just after you click "+" ?

**Review by erwanp — APPROVED** [review]

**Comment by suzil** [comment]
Added auto-focus of molecule input @erwanp 
https://user-images.githubusercontent.com/13723264/105380221-40e66480-5bd3-11eb-8289-b073affcffb9.mov

**Review by erwanp — APPROVED** [review]

**Comment by erwanp** [comment]
Very nice ! 

Let's merge ??    @ulyssed will be happy, it's his code for multi-molecule that's used in the backend !

**Pull request merged**
